a = (2,4,5,3,2)
a[0] =45

# Should be getting the below error  
'''Traceback (most recent call last):
  File "/Users/praveenbhogade/praveen_coding/python_stuff/4. CHAPTER 4/08_pr_03_tuple_change_test.py", line 2, in <module>
    a[0] =45
TypeError: 'tuple' object does not support item assignment'''